### ISSUE TITLE
How is the OpenAPI UI generated?

### ISSUE THREAD

**Issue by yurishkuro** [gogo/grpc-example#14]
I see a number of static assets added in https://github.com/gogo/grpc-example/commit/a6e1cf36babfecf2dd04238aee48c736445036c7, but no indication where they came from. The option `--swagger_out=third_party/OpenAPI/` to `protoc` only generates the JSON file. If I want to serve swagger UI from my application, how would I go about generating them?  I don't want to just copy them from this repo. 

I'm happy to create a PR with example/explanation if you point me in the right direction.

**Comment by johanbrandhorst** [comment]
Hi!

The request/reply elements are all dynamically generated from the generated `swagger.json` file by [swagger-ui.js](https://github.com/gogo/grpc-example/blob/2cbb4353371148b4a6259cd1795363aa3c6ef180/third_party/OpenAPI/swagger-ui.js). The contents of the third_party/OpenAPI folder are copied directly from the [dist folder](https://github.com/swagger-api/swagger-ui/tree/11c586309fa6c0e952b7e40ca46350f9af23b6e5/dist) of the OpenAPI-UI project.

You're welcome to create a PR to clarify this in the README if you think it's unclear and should be added.
