### ISSUE TITLE
AddUser method panics

### ISSUE THREAD

**Issue by sevein** [gogo/grpc-example#29]
Hi there! I really appreciate the time spent putting this example together - it's pretty awesome!

Testing it locally, I've found that the [server panics](https://gist.github.com/sevein/5642f8343be78ada639e470199302ea5) in the AddUser method when I connect the client.

I managed to fix it by returning a `&types.Empty{}` instead of `nil`. I'm curious to know why that didn't happen to the person writing it! These are my changes: https://gist.github.com/sevein/ddbec1c4e00ea3c3e1c14c8efb5c335b.

**Comment by johanbrandhorst** [comment]
Ah, this is because I recently updated the dependencies. Could you submit a pull request with your changes?
