### ISSUE TITLE
how to replace google's protos when used in grpc gateway request

### ISSUE THREAD

**Issue by kaisawind** [gogo/grpc-example#33]
For example
```proto
// The file manager service definition.
service FileManager {
    rpc Hello(google.protobuf.Empty) returns (google.protobuf.Empty) {
        option (google.api.http) = {
            get: "/v1/hello"
        };
        option (grpc.gateway.protoc_gen_swagger.options.openapiv2_operation) = {
            responses: {
                key: "200"
            }
        };
    }
}
```
the code will be generate just like below
```go
func request_FileManager_Hello_0(ctx context.Context, marshaler runtime.Marshaler, client FileManagerClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq empty.Empty
	var metadata runtime.ServerMetadata

	msg, err := client.Hello(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}
```

`empty.Empty` can not be found by go when it be replaced by `github.com/gogo/protobuf/types`.
How can i fix it?

**Comment by johanbrandhorst** [comment]
This is fixed by using an M import parameter. See https://jbrandhorst.com/post/go-protobuf-tips/ for an example.

**Comment by kaisawind** [comment]
@johanbrandhorst 
Maybe I didn't make it clear,I'm sorry about that.

We can use M to fix import packages, but how about really codes?
`*.pb.go` has been changed, but `*pb.gw.go` not.
Please take a look at `empty.Empty`.

`*.pb.go`
![20200330031600](https://user-images.githubusercontent.com/4010613/77858278-120e9480-7235-11ea-8b53-34cce3511eb4.png)
`*pb.gw.go`
![20200330031624](https://user-images.githubusercontent.com/4010613/77858281-163ab200-7235-11ea-8cd0-644a7fc155da.png)

**Comment by kaisawind** [comment]
By the way, all `*.pb.go` and `*pb.gw.go` imports have been changed.

`*.pb.go`
![20200330032315](https://user-images.githubusercontent.com/4010613/77858431-17201380-7236-11ea-8e36-5534378e6d9d.png)
`*pb.gw.go`
![20200330032302](https://user-images.githubusercontent.com/4010613/77858433-1ab39a80-7236-11ea-83ac-e7f070385969.png)

**Comment by johanbrandhorst** [comment]
That one is a bug in the gRPC gateway generator. See https://jbrandhorst.com/post/gogoproto/

**Comment by kaisawind** [comment]
> That one is a bug in the gRPC gateway generator. See https://jbrandhorst.com/post/gogoproto/

Thank you very much.
