### ISSUE TITLE
Open source license missing?

### ISSUE THREAD

**Issue by mike-jm** [gogo/grpc-example#37]
Hello!

Could you please consider putting this repo under an open source license?
I am asking because I working in an environment that has a regulation in place that forbids using this example as a starting point when it is not under an open source license.
Preferable would be a permissive open source license like MIT or Apache 2.0
But that is up to you.

Many regards,

Michael

**Comment by johanbrandhorst** [comment]
Hi Michael! Thanks for your issue. I'd be happy to add a license to the repository, but I want to warn you that `gogo/protobuf` is not currently maintained (https://github.com/gogo/protobuf/issues/691), so you probably don't want to use this example as a basis for any new project.
