### ISSUE TITLE
Create CI test that ensure generated files have not changed

### ISSUE THREAD

**Issue by johanbrandhorst** [gogo/grpc-example#5]
It can use the scripts from gogo/googleapis as mentioned in https://github.com/gogo/grpc-example/pull/4#discussion_r170446725.

This should include splitting the third_party folder generation assets into a separate Makefile job as it is generation-time dependant.

**Comment by awalterschulze** [comment]
Sounds good.

Are you able to create a travis job, now that you are a member of gogo?

**Comment by johanbrandhorst** [comment]
I added Travis to the repo but when I triggered a build it failed. I will look into it later, a bit busy today. Feel free to fix it if you know what's missing. I have no prior experience with Travis.

**Comment by awalterschulze** [comment]
Take your time.

Is there some other free builder you do have experience with?

**Comment by johanbrandhorst** [comment]
I use an advanced CircleCI setup to test the GopherJS gRPC-web bindings, but I want to learn to use Travis too :).

**Comment by awalterschulze** [comment]
I have heard good things about circle ci, so it is definitely an option
instead of travis, but your choice.
